services:
  steampipe:
    build:
      context: .
      dockerfile: Dockerfile.offline
    container_name: steampipe
    ports:
      - "9193:9193"
    volumes:
      - ./config:/home/steampipe/.steampipe/config
    restart: unless-stopped
